Ensure running `-PerrorProneSuppress` and `-PerrorProneApply` at the same time do not resolve Configurations at configuration time (#141)
Ensure running `-PerrorProneSuppress` and `-PerrorProneApply` at the same time when an `IfModuleIsUsed` conditional patch check is in use do not resolve Configurations at configuration time, which cause this error when used with `gradle-consistent-versions`:

```
org.gradle.api.GradleException: Not allowed to resolve configuration ':project:integrationTestCompileClasspath' at configuration time (https://guides.gradle.org/performance/#don_t_resolve_dependencies_at_configuration_time). Please upgrade your plugins and double-check your gradle scripts (see stacktrace)
```